.\" This file is part of the Ssstr string library.
.\" Copyright 2022-2023 Board of Regents of the University of Wisconsin System
.\" SPDX-License-Identifier: MIT
.\"
.TH SS8_COPY_TO_CSTR 3  2023-12-30 SSSTR "Ssstr Manual"
.SH NAME
ss8_copy_to_cstr, ss8_copy_to_bytes \- copy an ssstr byte string to a buffer
.SH SYNOPSIS
.nf
.B #include <ss8str.h>
.PP
.BI "bool ss8_copy_to_cstr(ss8str const *restrict " str ","
.BI "                      char *restrict " buf ", size_t " bufsize ");"
.BI "bool ss8_copy_to_bytes(ss8str const *restrict " str ","
.BI "                      char *restrict " buf ", size_t " bufsize ");"
.fi
.SH DESCRIPTION
.BR ss8_copy_to_cstr ()
copies the contents of the
.B ss8str
at
.I str
to the buffer located at
.IR buf ,
and appends a null byte.
At most
.I bufsize
bytes are written, including the null terminator; if
.I bufsize
is not sufficient to hold the string, the copied string is truncated at
.IB bufsize " - 1"
bytes.
.PP
Behavior is undefined unless
.I str
is a valid
.B ss8str
object,
.I buf
points to a buffer of at least
.I bufsize
bytes that does not overlap with the internal buffer of
.IR str ,
and
.I bufsize
is greater than or equal to 1.
.PP
.BR ss8_copy_to_bytes ()
copies the contents of the
.B ss8str
at
.I str
to the buffer located at
.IR buf .
No null terminator is appended.
At most
.I bufsize
bytes are written; if
.I bufsize
is not sufficient to hold the string, the copied string is truncated at
.I bufsize
bytes.
.PP
Behavior is undefined unless
.I str
is a valid
.B ss8str
object and
.I buf
points to a buffer of at least
.I bufsize
bytes that does not overlap with the internal buffer of
.IR str .
.SH RETURN VALUE
.BR ss8_copy_to_cstr ()
and
.BR ss8_copy_to_bytes ()
return
.B true
if the whole of the string
.I str
was copied.
If the string had to be truncated, they return
.BR false .
.SH SEE ALSO
.BR ss8_copy_bytes (3),
.BR ss8_copy_cstr (3),
.BR ssstr (7)
