# This file is part of the Ssstr string library.
# Copyright 2022, Board of Regents of the University of Wisconsin System
# SPDX-License-Identifier: MIT

[tool.black]
line-length = 79
target-version = ['py39']
